[package]
name = "whereami"
version = "0.1.0"
authors = ["Kyle Isom <kyle@imap.cc>"]

[dependencies]
actix-web = "0.7.14"
rusqlite = "0.15.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
time = "0.1.40"
